### 1. Configuration

In [183]:
import pandas as pd

In [184]:
df_customer = pd.read_csv("olist_customers_dataset.csv")
df_geolocation = pd.read_csv("olist_geolocation_dataset.csv")
df_order_items = pd.read_csv("olist_order_items_dataset.csv")
df_order_payments = pd.read_csv("olist_order_payments_dataset.csv")
df_order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
df_orders = pd.read_csv("olist_orders_dataset.csv")
df_products = pd.read_csv("olist_products_dataset.csv")
df_sellers  = pd.read_csv("olist_sellers_dataset.csv")
df_product_translation = pd.read_csv("product_category_name_translation.csv")

list_df = { 
    "df_customer": df_customer,
    "df_geolocation": df_geolocation,
    "df_order_items": df_order_items,
    "df_order_payments": df_order_payments,
    "df_order_reviews": df_order_reviews,
    "df_orders": df_orders,
    "df_products": df_products,
    "df_sellers": df_sellers,
    "df_product_translation": df_product_translation
    }

##### **1. df_customer**

| column                               | description                                                             |
|--------------------------------------|-------------------------------------------------------------------------|
| `customer_id`                        | key to the order dataset; each order has a unique customer_id           |
| `customer_unique_id`                 | unique identifier of the customer                                       |
| `customer_zip_code_prefix`           | first five digits of the ZIP code (without leading zeros)               |
| `customer_city`                      | customer city name                                                      |
| `customer_state`                     | customer state (UF/FS)                                                  |

##### **2. df_geolocation**

| column                               | description                                                             |
|--------------------------------------|-------------------------------------------------------------------------|
| `geolocation_zip_code_prefix`        | first five digits of the ZIP code (without leading zeros)               |
| `geolocation_lat`                    | latitude coordinates                                                    |
| `geolocation_lng`                    | longitude coordinates                                                   |
| `geolocation_city`                   | city name                                                               |
| `geolocation_state`                  | federative state                                                        |

##### **3. df_order_items**

| column                               | description                                                             |
|--------------------------------------|-------------------------------------------------------------------------|
| `order_id`                           | order unique id                                                         |
| `order_item_id`                      | sequential number identyfing number of items included in the same order |
| `product_id`                         | product unique idetifier                                                |
| `seller_id`                          | seller unique identifier                                                |
| `shipping_limit_date`                | seller shipping limit date to handling the order to logistic partner    |
| `price`                              | item price (for each product)                                           |
| `freight_value`                      | freight value (for each product)                                        |

##### **4. df_order_payments**

| column                               | description                                                             |
|--------------------------------------|-------------------------------------------------------------------------|
| `order_id`                           | order unique id                                                         |
| `payment_sequential`                 | if the customer pay order with more than one method  it'll show here    |
| `payment_type`                       | method of payment chosen by the customer                                |
| `payment_installments`               | number of installments chosen by the customer                           |
| `payment_value`                      | transaction value                                                       |

##### **5. df_order_reviews**

| column                               | description                                                             |
|--------------------------------------|-------------------------------------------------------------------------|
| `review_id`                          | review unique id                                                        |
| `order_id`                           | order unique id                                                         |
| `review_score`                       | note of the satisfaction survey                                         |
| `review_comment_title`               | comment title from the review (Portuguese)                              |
| `review_comment_message`             | comment message from the review (Portuguese)                            |
| `review_creation_date`               | date when satisfaction survey was sent to the customer                  |
| `review_answer_timestamp`            | date when satisfation suvery was answered                               |

##### **6. df_orders**

| column                               | description                                                             |
|--------------------------------------|-------------------------------------------------------------------------|
| `order_id`                           | order unique id                                                         |
| `customer_id`                        | customer unique id                                                      |
| `order_status`                       | order status                                                            |
| `order_purchase_timestamp`           | purchase timestamp                                                      |
| `order_approved_at`                  | payment approval timestamp                                              |
| `order_delivered_carrier_date`       | order posting timestamp (handled to the logist partner)                 |
| `order_delivered_customer_date`      | order delivered to the customer                                         |
| `order_estimated_delivery_date`      | the estimated delivery date showed to the customer                      |


##### **7. df_products**

| column                               | description                                                             |
|--------------------------------------|-------------------------------------------------------------------------|
| `product_id`                         | product unique identifier                                               |
| `product_category_name`              | root category of product (Portuguese)                                   |
| `product_name_lenght`                | number of characters from the product name                              |
| `product_description_lenght`         | number of characters from the description                               |
| `product_photos_qty`                 | number of product published photos                                      |
| `product_weight_g`                   | product weight measured in grams                                        |
| `product_length_cm`                  | product lenght measured in centimeters                                  |
| `product_height_cm`                  | product height measured in centimeters                                  |
| `product_width_cm`                   | product width measured in centimeters                                   |

##### **8. df_sellers**

| column                               | description                                                             |
|--------------------------------------|-------------------------------------------------------------------------|
| `seller_id`                          | seller unique identifier                                                |
| `seller_zip_code_prefix`             | first five digits of the seller ZIP code (without leading zeros)        |
| `seller_city`                        | seller city                                                             |
| `seller_state`                       | seller state (UF/FS)                                                    |

##### **9. df_product_translation**

| column                               | description                                                             |
|--------------------------------------|-------------------------------------------------------------------------|
| `product_category_name`              | category name in Portuguese                                             |
| `product_category_name_english`      | category name in English                                                |

### 2. Exploring Datasets

In [185]:
df_customer.head(2)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP

In [186]:
df_geolocation.head(2)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP

In [187]:
df_order_items.head(2)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

In [188]:
df_order_payments.head(2)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39

In [189]:
df_order_reviews.head(2)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13

In [190]:
df_orders.head(2)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00

In [191]:
df_products.head(2)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0

In [192]:
df_sellers.head(2)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP

In [193]:
df_product_translation.head(2)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories

### 3. Informations of datasets

#### 3.1. Basic data

In [194]:
# Lenght of datasets

for key, value in list_df.items():
    print(f"{key}: {len(value)} items." )

df_customer: 99441 items.
df_geolocation: 1000163 items.
df_order_items: 112650 items.
df_order_payments: 103886 items.
df_order_reviews: 99224 items.
df_orders: 99441 items.
df_products: 32951 items.
df_sellers: 3095 items.
df_product_translation: 71 items.

#### 3.2. NULL Data Treatment

In [195]:
for df_name, df in list_df.items():
    print(f"{df_name}")
    print(df.isnull().sum())
    print()

# df_customer, df_geolocation, df_order_items, df_order_payments, df_sellers -> No NULL
# df_order_reviews -> NULL just in text columns, replace with "no comment"
# df_orders -> NULL bring information of status of order -> no approved, no delivered to customer ou no delivered to logistic partner -> it will not be alterations
# df_products -> columns of name and category means product with no identification | columns of measures -> replace with mode or mean (just 2)
# df_product_translation -> just support df

df_customer
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

df_geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

df_order_items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

df_order_payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

df_order_reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

df_orders
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

df_products
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

df_sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

df_product_translation
product_category_name            0
product_category_name_english    0
dtype: int64

In [196]:
# df_order_reviews
# -> replace with "no comment"
fill = ["review_comment_title", "review_comment_message"]

df_order_reviews[fill] = df_order_reviews[fill].fillna("no_comments")
df_order_reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [197]:
# df_products
# -> columns that means that we no have info, we need to put this
# -> columns that with the measure of two products, 1 we will input the mode of category and 1 we wil remove

no_info = ["product_category_name", "product_name_lenght", "product_description_lenght", "product_photos_qty"]
mean_info = ["product_weight_g", "product_length_cm", "product_height_cm", "product_width_cm"]

In [198]:
df_products[no_info] = df_products[no_info].fillna("no_information")

for i in mean_info:
    X = df_products.loc[df_products["product_category_name"] == "bebes", i].mode()[0]
    df_products.loc[df_products["product_id"] == "09ff539a621711667c43eba6a3bd8466", i] = X

df_products = df_products[df_products["product_id"] != "5eb564652db742ff8f28759cd8d2652a"]

df_products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

#### 3.3. Tranforming the datasets

In [225]:
# df_order_items -> need to agroup the information because we have more than 1 line per order

columns = ["order_item_id", "price", "freight_value"]

df_order_items = df_order_items.groupby(by="order_id", as_index=False)[columns].agg(
                                                    total_items = ("order_item_id", "count"),
                                                    order_total_price = ("price", "sum"),
                                                    freight_total_price = ("freight_value", "sum")
                                                    )

df_order_items.head(2)

,order_id,total_items,order_total_price,freight_total_price
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,239.9,19.93

In [ ]:
# df_customer -> we have customer_unique_id as the true customer identifier, but we have to connect the table with customer_id

In [232]:
df_order_payments[df_order_payments["order_id"] == "fa65dad1b0e818e3ccc5cb0e39231352"].sort_values(by="payment_sequential")

,order_id,payment_sequential,payment_type,payment_installments,payment_value
14321,fa65dad1b0e818e3ccc5cb0e39231352,1,voucher,1,3.71
23074,fa65dad1b0e818e3ccc5cb0e39231352,2,voucher,1,8.51
65641,fa65dad1b0e818e3ccc5cb0e39231352,3,voucher,1,2.95
9985,fa65dad1b0e818e3ccc5cb0e39231352,4,voucher,1,29.16
28330,fa65dad1b0e818e3ccc5cb0e39231352,5,voucher,1,0.66
29648,fa65dad1b0e818e3ccc5cb0e39231352,6,voucher,1,5.02
82593,fa65dad1b0e818e3ccc5cb0e39231352,7,voucher,1,0.32
68853,fa65dad1b0e818e3ccc5cb0e39231352,8,voucher,1,26.02
17274,fa65dad1b0e818e3ccc5cb0e39231352,9,voucher,1,1.08
19565,fa65dad1b0e818e3ccc5cb0e39231352,10,voucher,1,12.86
32519,fa65dad1b0e818e3ccc5cb0e39231352,11,voucher,1,4.03
73537,fa65dad1b0e818e3ccc5cb0e39231352,12,voucher,1,3.60
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.00
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.00
63369,fa65dad1b0e818e3ccc5cb0e39231352,15,voucher,1,14.04
78050,fa65dad1b0e818e3ccc5cb0e39231352,16,voucher,1,12.86
79670,fa65dad1b0e818e3ccc5cb0e39231352,17,voucher,1,3.72
80321,fa65dad1b0e818e3ccc5cb0e39231352,18,voucher,1,0.73
74721,fa65dad1b0e818e3ccc5cb0e39231352,19,voucher,1,5.02
93337,fa65dad1b0e818e3ccc5cb0e39231352,20,voucher,1,150.00
74239,fa65dad1b0e818e3ccc5cb0e39231352,21,voucher,1,4.11
100606,fa65dad1b0e818e3ccc5cb0e39231352,22,voucher,1,4.03
85166,fa65dad1b0e818e3ccc5cb0e39231352,23,voucher,1,18.86
99213,fa65dad1b0e818e3ccc5cb0e39231352,24,voucher,1,0.42
24879,fa65dad1b0e818e3ccc5cb0e39231352,25,voucher,1,3.68
79587,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.27
4885,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.02
39111,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.05
39108,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.26

#### 3.4. Final Dataset

In [226]:
df_order_items.head()

,order_id,total_items,order_total_price,freight_total_price
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14